/**
 * Accessors for the real campus geometry captured from OpenStreetMap.
 *
 * The geometry file is generated by `scripts/build-campus-geometry.mts` from the
 * Overpass API. It is committed, so the running app never depends on Overpass.
 * Nothing in this module invents geometry: every coordinate here traces back to
 * an OSM way or relation.
 *
 * Attribution: (c) OpenStreetMap contributors, ODbL 1.0. Must be displayed in
 * the UI wherever this data is shown.
 */

export interface Footprint {
  id: string;
  name: string | null;
  footprint: [number, number][];
  area_m2: number;
}

export interface CampusBuilding extends Footprint {
  /** Real height in metres when OSM records it, otherwise null. Never invented. */
  height_m: number | null;
  levels: number | null;
  building_type: string;
  kind_hint: string | null;
}

export interface CampusRoad {
  id: string;
  name: string | null;
  highway: string;
  surface: string | null;
  line: [number, number][];
}

export interface CampusArea extends Footprint {
  sport?: string;
}

export interface CampusPoint {
  id: string;
  x: number;
  y: number;
  kind: string;
  name?: string | null;
}

export interface CampusGeometry {
  $schema: 'campus-geometry/v1';
  source: string;
  source_url: string;
  captured_at: string;
  centre: { lat: number; lon: number };
  radius_m: number;
  projection: string;
  counts: Record<string, number>;
  buildings: CampusBuilding[];
  roads: CampusRoad[];
  sports: CampusArea[];
  green: CampusArea[];
  water: CampusArea[];
  parking: CampusArea[];
  wood: CampusArea[];
  trees: CampusPoint[];
  other: (CampusArea & { kind: string })[];
}

import geometryJson from '../data/campus-geometry.json' with { type: 'json' };

export const CAMPUS_GEOMETRY = geometryJson as unknown as CampusGeometry;

export const OSM_ATTRIBUTION = '© OpenStreetMap contributors (ODbL 1.0)';
export const SATELLITE_ATTRIBUTION = 'Imagery © Esri, Maxar, Earthstar Geographics';

/** Degrees per metre at the capture latitude, for tiles and scale bars. */
const M_PER_DEG_LAT = 111_320;
const M_PER_DEG_LON = M_PER_DEG_LAT * Math.cos((CAMPUS_GEOMETRY.centre.lat * Math.PI) / 180);

/** Converts the local metre grid back to WGS84. Used for tiles and scale. */
export function localToLatLon(x: number, y: number): { lat: number; lon: number } {
  return {
    lat: CAMPUS_GEOMETRY.centre.lat + y / M_PER_DEG_LAT,
    lon: CAMPUS_GEOMETRY.centre.lon + x / M_PER_DEG_LON
  };
}

/** Converts WGS84 into the local metre grid. */
export function latLonToLocal(lat: number, lon: number): [number, number] {
  return [
    (lon - CAMPUS_GEOMETRY.centre.lon) * M_PER_DEG_LON,
    (lat - CAMPUS_GEOMETRY.centre.lat) * M_PER_DEG_LAT
  ];
}

/**
 * Web Mercator tile coordinates for the campus extent.
 *
 * Standard slippy-map maths. `z` is chosen automatically so the whole campus fits
 * in a fixed request budget: at z=18 this campus needs 210 tiles and a 52 MB
 * compositing canvas, which is slow to load and will fail on a low-memory phone.
 * `maxTiles` is the ceiling, and the zoom steps down until the range fits.
 */
export function campusTileRange(z: number, maxTiles = 64): {
  z: number;
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
  count: number;
  /** True when the requested zoom had to be reduced to respect the budget. */
  reduced: boolean;
} {
  let chosen = z;
  let range = tileRangeAt(chosen);
  while (range.count > maxTiles && chosen > 10) {
    chosen -= 1;
    range = tileRangeAt(chosen);
  }
  return { ...range, reduced: chosen !== z };
}

function tileRangeAt(z: number) {
  const n = 2 ** z;
  const r = CAMPUS_GEOMETRY.radius_m;
  const nw = localToLatLon(-r, -r);
  const se = localToLatLon(r, r);
  const a = toTile(nw.lat, nw.lon, n);
  const b = toTile(se.lat, se.lon, n);

  const minX = Math.min(a.x, b.x);
  const maxX = Math.max(a.x, b.x);
  const minY = Math.min(a.y, b.y);
  const maxY = Math.max(a.y, b.y);

  return { z, minX, maxX, minY, maxY, count: (maxX - minX + 1) * (maxY - minY + 1) };
}

function toTile(lat: number, lon: number, n: number) {
  const latRad = (lat * Math.PI) / 180;
  return {
    x: Math.floor(((lon + 180) / 360) * n),
    y: Math.floor(
      ((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2) * n
    )
  };
}

/** Metres covered by one tile at this zoom, for scale bars. */
export function metresPerPixel(z: number): number {
  const n = 2 ** z;
  return (2 * Math.PI * 6_378_137) / (256 * n);
}

/**
 * Height used for a building massing.
 *
 * When OSM records a real height, that is used. When it does not, a documented
 * default is applied and the building is flagged so the UI can say the height is
 * assumed rather than surveyed. The alternative - a random height per building -
 * would look plausible and mean nothing.
 */
export const DEFAULT_BUILDING_HEIGHT_M = 12;

export function massingHeight(building: CampusBuilding): {
  metres: number;
  source: 'osm' | 'assumed';
} {
  if (building.height_m != null && building.height_m > 1) {
    return { metres: building.height_m, source: 'osm' };
  }
  if (building.levels != null && building.levels > 0) {
    return { metres: Math.round(building.levels * 3.2), source: 'osm' };
  }
  return { metres: DEFAULT_BUILDING_HEIGHT_M, source: 'assumed' };
}

/** Counts how many buildings have a surveyed height, for honest reporting. */
export function geometryProvenance(): {
  total: number;
  surveyed: number;
  assumed: number;
  roads: number;
  namedBuildings: string[];
} {
  const surveyed = CAMPUS_GEOMETRY.buildings.filter(
    b => b.height_m != null || b.levels != null
  ).length;
  return {
    total: CAMPUS_GEOMETRY.buildings.length,
    surveyed,
    assumed: CAMPUS_GEOMETRY.buildings.length - surveyed,
    roads: CAMPUS_GEOMETRY.roads.length,
    namedBuildings: CAMPUS_GEOMETRY.buildings
      .map(b => b.name)
      .filter((n): n is string => Boolean(n))
  };
}

/** Builds a spatial index so a click or a route lookup stays O(log n). */
export class FootprintIndex {
  private readonly cells = new Map<string, CampusBuilding[]>();
  private readonly cellSize = 120;

  constructor(private readonly buildings: CampusBuilding[]) {
    for (const b of buildings) {
      for (const key of this.keysFor(b.footprint)) {
        const list = this.cells.get(key);
        if (list) list.push(b);
        else this.cells.set(key, [b]);
      }
    }
  }

  private key(cx: number, cy: number): string {
    return `${cx}:${cy}`;
  }

  private *keysFor(ring: [number, number][]): Generator<string> {
    const xs = ring.map(p => p[0]);
    const ys = ring.map(p => p[1]);
    const c0 = Math.floor(Math.min(...xs) / this.cellSize);
    const c1 = Math.floor(Math.max(...xs) / this.cellSize);
    const r0 = Math.floor(Math.min(...ys) / this.cellSize);
    const r1 = Math.floor(Math.max(...ys) / this.cellSize);
    for (let cx = c0; cx <= c1; cx++) {
      for (let cy = r0; cy <= r1; cy++) yield this.key(cx, cy);
    }
  }

  /** Nearest footprint to a point, within `maxMetres`. */
  nearest(x: number, y: number, maxMetres = 60): CampusBuilding | null {
    const cx = Math.floor(x / this.cellSize);
    const cy = Math.floor(y / this.cellSize);
    let best: CampusBuilding | null = null;
    let bestDist = maxMetres * maxMetres;

    for (let i = -1; i <= 1; i++) {
      for (let j = -1; j <= 1; j++) {
        const list = this.cells.get(this.key(cx + i, cy + j));
        if (!list) continue;
        for (const b of list) {
          if (pointInRing(x, y, b.footprint)) return b;
          const d = distanceToRing(x, y, b.footprint);
          if (d < bestDist) {
            bestDist = d;
            best = b;
          }
        }
      }
    }
    return best;
  }
}

export function pointInRing(x: number, y: number, ring: [number, number][]): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

export function distanceToRing(x: number, y: number, ring: [number, number][]): number {
  let best = Infinity;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const d = distanceToSegment(x, y, ring[j], ring[i]);
    if (d < best) best = d;
  }
  return best;
}

/** Exported so the route graph can measure approach distance on the same maths. */
export function distanceToSegment(
  px: number,
  py: number,
  a: [number, number],
  b: [number, number]
): number {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const lenSq = dx * dx + dy * dy;
  if (lenSq === 0) return Math.hypot(px - a[0], py - a[1]);
  let t = ((px - a[0]) * dx + (py - a[1]) * dy) / lenSq;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(px - (a[0] + t * dx), py - (a[1] + t * dy));
}

/** Area-weighted centroid of a ring, used to place labels and beacons. */
export function ringCentroid(ring: [number, number][]): [number, number] {
  let area = 0;
  let cx = 0;
  let cy = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const cross = ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1];
    area += cross;
    cx += (ring[j][0] + ring[i][0]) * cross;
    cy += (ring[j][1] + ring[i][1]) * cross;
  }
  if (Math.abs(area) < 1e-6) {
    const xs = ring.map(p => p[0]);
    const ys = ring.map(p => p[1]);
    return [xs.reduce((a, b) => a + b, 0) / xs.length, ys.reduce((a, b) => a + b, 0) / ys.length];
  }
  return [cx / (3 * area), cy / (3 * area)];
}
